import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Loker.id",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="w-full h-screen bg-white overflow-auto flex flex-col">
          <Navbar />
          <div className="grow">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
